{
  "defaultArtifact": {
    "artifactAccount": "{{ var "githubAccount" }}",
    "name": "{{ var "artifactPath" }}",
    "reference": "{{ var "reference" }}",
    "type": "github/file",
    "version": "{{ var "version" }}"
  },
  "displayName": "{{ var "displayName" }}",
  "id": "{{ var "expectedArtifactId" }}",
  "matchArtifact": {
    "artifactAccount": "{{ var "githubAccount" }}",
    "customKind": true,
    "name": "{{ var "artifactPath" }}",
    "type": "github/file"
  },
  "useDefaultArtifact": false,
  "usePriorArtifact": true
}