{
	"account": "{{ var "k8sProviderName" }}",
	"cloudProvider": "kubernetes",
	"manifestArtifact": {{ module "k8s.manifestart.module" "artifactPath" "spin-apps/acmeair/acme-air-dep.yml" "githubAccount" "garreeoke" "branch" "master"}},
	"moniker": {
				"app": "{{ var "app" }}"
	},
	"name": "{{ var "stageName" }}",
	"refId": "{{ var "stageOrder" }}",
	"requisiteStageRefIds": [],
	"skipExpressionEvaluation": false,
	"source": "artifact",
	"trafficManagement": {
		"enabled": false,
		"options": {
			"enableTraffic": false,
			"services": []
		}
	},
	"type": "deployManifest"
}