{
      "failPipeline": true,
      "instructions": "{{ var "instruction" }}",
      "judgmentInputs": [
        {
          "value": "{{ var "judgementInput" }}"
        }
      ],
      "name": "{{ var "stageName" }}",
      "notifications": [
         {{ module "slack.notification.module" }}
      ],
      "refId": "{{ var "stageOrder" }}",
      "requisiteStageRefIds": [
        "{{ var "previousStage" }}"
      ],
      "type": "manualJudgment",
      "sendNotifications": {{ var "sendNotifications" ?: false }}
    }