{
	"action": "{{ var "terraformAction" }}",
	"artifacts": [
	  {{ module "github.artifact.module" }}
	],
	"expectedArtifacts": [
       {{ module "github.expectedart.module" "expectedArtifactId" "some-artifact-id" "displayName" "acmenode-deployment" }}
	],
	"name": "{{ var "stageName" }}",
	"overrides": {
		"environment_name": "{{ var "env_name" }}"
	},
	"profile": "",
	"targets": [],
	"terraformVersion": "{{ var "terraformVersion" }}",
	"type": "terraform",
	"workspace": "{{ var "workspace" }}"
}